/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSetoresRouteImport } from './routes/_authenticated/setores'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedLocaisRouteImport } from './routes/_authenticated/locais'
import { Route as AuthenticatedLeitosRouteImport } from './routes/_authenticated/leitos'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedFarmaciaClinicaRouteImport } from './routes/_authenticated/farmacia-clinica'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedDispensacoesRouteImport } from './routes/_authenticated/dispensacoes'
import { Route as AuthenticatedDevolucoesRouteImport } from './routes/_authenticated/devolucoes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCentroCirurgicoRouteImport } from './routes/_authenticated/centro-cirurgico'
import { Route as AuthenticatedAlmoxarifadoRouteImport } from './routes/_authenticated/almoxarifado'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/_authenticated/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSetoresRoute = AuthenticatedSetoresRouteImport.update({
  id: '/_authenticated/setores',
  path: '/setores',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/_authenticated/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/_authenticated/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLocaisRoute = AuthenticatedLocaisRouteImport.update({
  id: '/_authenticated/locais',
  path: '/locais',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeitosRoute = AuthenticatedLeitosRouteImport.update({
  id: '/_authenticated/leitos',
  path: '/leitos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/_authenticated/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFarmaciaClinicaRoute =
  AuthenticatedFarmaciaClinicaRouteImport.update({
    id: '/_authenticated/farmacia-clinica',
    path: '/farmacia-clinica',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/_authenticated/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDispensacoesRoute =
  AuthenticatedDispensacoesRouteImport.update({
    id: '/_authenticated/dispensacoes',
    path: '/dispensacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDevolucoesRoute = AuthenticatedDevolucoesRouteImport.update({
  id: '/_authenticated/devolucoes',
  path: '/devolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/_authenticated/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCentroCirurgicoRoute =
  AuthenticatedCentroCirurgicoRouteImport.update({
    id: '/_authenticated/centro-cirurgico',
    path: '/centro-cirurgico',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAlmoxarifadoRoute =
  AuthenticatedAlmoxarifadoRouteImport.update({
    id: '/_authenticated/almoxarifado',
    path: '/almoxarifado',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/almoxarifado': typeof AuthenticatedAlmoxarifadoRoute
  '/centro-cirurgico': typeof AuthenticatedCentroCirurgicoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/devolucoes': typeof AuthenticatedDevolucoesRoute
  '/dispensacoes': typeof AuthenticatedDispensacoesRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/farmacia-clinica': typeof AuthenticatedFarmaciaClinicaRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/leitos': typeof AuthenticatedLeitosRoute
  '/locais': typeof AuthenticatedLocaisRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/setores': typeof AuthenticatedSetoresRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/almoxarifado': typeof AuthenticatedAlmoxarifadoRoute
  '/centro-cirurgico': typeof AuthenticatedCentroCirurgicoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/devolucoes': typeof AuthenticatedDevolucoesRoute
  '/dispensacoes': typeof AuthenticatedDispensacoesRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/farmacia-clinica': typeof AuthenticatedFarmaciaClinicaRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/leitos': typeof AuthenticatedLeitosRoute
  '/locais': typeof AuthenticatedLocaisRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/setores': typeof AuthenticatedSetoresRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/_authenticated/almoxarifado': typeof AuthenticatedAlmoxarifadoRoute
  '/_authenticated/centro-cirurgico': typeof AuthenticatedCentroCirurgicoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/devolucoes': typeof AuthenticatedDevolucoesRoute
  '/_authenticated/dispensacoes': typeof AuthenticatedDispensacoesRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/farmacia-clinica': typeof AuthenticatedFarmaciaClinicaRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/leitos': typeof AuthenticatedLeitosRoute
  '/_authenticated/locais': typeof AuthenticatedLocaisRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/setores': typeof AuthenticatedSetoresRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/almoxarifado'
    | '/centro-cirurgico'
    | '/configuracoes'
    | '/devolucoes'
    | '/dispensacoes'
    | '/estoque'
    | '/farmacia-clinica'
    | '/inventario'
    | '/leitos'
    | '/locais'
    | '/produtos'
    | '/relatorios'
    | '/setores'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/almoxarifado'
    | '/centro-cirurgico'
    | '/configuracoes'
    | '/devolucoes'
    | '/dispensacoes'
    | '/estoque'
    | '/farmacia-clinica'
    | '/inventario'
    | '/leitos'
    | '/locais'
    | '/produtos'
    | '/relatorios'
    | '/setores'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/_authenticated/almoxarifado'
    | '/_authenticated/centro-cirurgico'
    | '/_authenticated/configuracoes'
    | '/_authenticated/devolucoes'
    | '/_authenticated/dispensacoes'
    | '/_authenticated/estoque'
    | '/_authenticated/farmacia-clinica'
    | '/_authenticated/inventario'
    | '/_authenticated/leitos'
    | '/_authenticated/locais'
    | '/_authenticated/produtos'
    | '/_authenticated/relatorios'
    | '/_authenticated/setores'
    | '/_authenticated/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AuthenticatedAlmoxarifadoRoute: typeof AuthenticatedAlmoxarifadoRoute
  AuthenticatedCentroCirurgicoRoute: typeof AuthenticatedCentroCirurgicoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDevolucoesRoute: typeof AuthenticatedDevolucoesRoute
  AuthenticatedDispensacoesRoute: typeof AuthenticatedDispensacoesRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFarmaciaClinicaRoute: typeof AuthenticatedFarmaciaClinicaRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedLeitosRoute: typeof AuthenticatedLeitosRoute
  AuthenticatedLocaisRoute: typeof AuthenticatedLocaisRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSetoresRoute: typeof AuthenticatedSetoresRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/setores': {
      id: '/_authenticated/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof AuthenticatedSetoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/locais': {
      id: '/_authenticated/locais'
      path: '/locais'
      fullPath: '/locais'
      preLoaderRoute: typeof AuthenticatedLocaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leitos': {
      id: '/_authenticated/leitos'
      path: '/leitos'
      fullPath: '/leitos'
      preLoaderRoute: typeof AuthenticatedLeitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/farmacia-clinica': {
      id: '/_authenticated/farmacia-clinica'
      path: '/farmacia-clinica'
      fullPath: '/farmacia-clinica'
      preLoaderRoute: typeof AuthenticatedFarmaciaClinicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dispensacoes': {
      id: '/_authenticated/dispensacoes'
      path: '/dispensacoes'
      fullPath: '/dispensacoes'
      preLoaderRoute: typeof AuthenticatedDispensacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/devolucoes': {
      id: '/_authenticated/devolucoes'
      path: '/devolucoes'
      fullPath: '/devolucoes'
      preLoaderRoute: typeof AuthenticatedDevolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/centro-cirurgico': {
      id: '/_authenticated/centro-cirurgico'
      path: '/centro-cirurgico'
      fullPath: '/centro-cirurgico'
      preLoaderRoute: typeof AuthenticatedCentroCirurgicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/almoxarifado': {
      id: '/_authenticated/almoxarifado'
      path: '/almoxarifado'
      fullPath: '/almoxarifado'
      preLoaderRoute: typeof AuthenticatedAlmoxarifadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AuthenticatedAlmoxarifadoRoute: AuthenticatedAlmoxarifadoRoute,
  AuthenticatedCentroCirurgicoRoute: AuthenticatedCentroCirurgicoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDevolucoesRoute: AuthenticatedDevolucoesRoute,
  AuthenticatedDispensacoesRoute: AuthenticatedDispensacoesRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFarmaciaClinicaRoute: AuthenticatedFarmaciaClinicaRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedLeitosRoute: AuthenticatedLeitosRoute,
  AuthenticatedLocaisRoute: AuthenticatedLocaisRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSetoresRoute: AuthenticatedSetoresRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
